export function getRandomNumbers(n) {
  let randomNumList = [];
  for (let i = 0; i < n; i++) {
    let randomNumber = Math.round(Math.random() * (460 - 2) + 2);
    let invalidList = [67, 78, 196, 197, 247, 287, 351, 359, 366, 431];
    if (
      invalidList.find(
        (element) =>
          element === randomNumber ||
          randomNumList.find((element) => element === randomNumber)
      )
    ) {
      randomNumber = Math.round(Math.random() * (460 - 2) + 2) + 1;
    }
    randomNumList.push(randomNumber);
  }
  return randomNumList;
}

export function newRenderPlayerList(n, playerList) {
  let newJumbledList = jumbleGivenList(playerList);
  let newCorrectList = jumbleGivenList(newJumbledList.slice(0, n));
  return newCorrectList;
}

export function jumbleGivenList(newArray) {
  let givenList = newArray;
  let currentIndex = givenList.length;
  let randomIndex;

  // While there remain elements to shuffle.
  while (currentIndex > 0) {
    // Pick a remaining element.
    randomIndex = Math.floor(Math.random() * currentIndex);
    currentIndex--;

    // And swap it with the current element.
    [givenList[currentIndex], givenList[randomIndex]] = [
      givenList[randomIndex],
      givenList[currentIndex],
    ];
  }

  return givenList;
}

export function mockData() {
  let mockD = [
    {
      resource: "players",
      id: 2,
      country_id: 52126,
      firstname: "Ahmed",
      lastname: "Shehzad",
      fullname: "Ahmed Shehzad",
      image_path: "https://cdn.sportmonks.com/images/cricket/players/2/2.png",
      dateofbirth: "1991-11-23",
      gender: "m",
      battingstyle: "right-hand-bat",
      bowlingstyle: "legbreak",
      position: {
        resource: "positions",
        id: 1,
        name: "Batsman",
      },
      updated_at: "2020-03-31T05:00:31.000000Z",
    },
    {
      resource: "players",
      id: 3,
      country_id: 52126,
      firstname: "Anwar",
      lastname: "Ali",
      fullname: "Anwar Ali",
      image_path: "https://cdn.sportmonks.com/images/cricket/players/3/3.png",
      dateofbirth: "1987-11-25",
      gender: "m",
      battingstyle: "right-hand-bat",
      bowlingstyle: "right-arm-fast-medium",
      position: {
        resource: "positions",
        id: 2,
        name: "Bowler",
      },
      updated_at: "2020-12-14T18:58:56.000000Z",
    },
    {
      resource: "players",
      id: 4,
      country_id: 52126,
      firstname: "Sarfraz",
      lastname: "Ahmed",
      fullname: "Sarfraz Ahmed",
      image_path: "https://cdn.sportmonks.com/images/cricket/players/4/4.png",
      dateofbirth: "1987-05-22",
      gender: "m",
      battingstyle: "right-hand-bat",
      bowlingstyle: "right-arm-offbreak",
      position: {
        resource: "positions",
        id: 3,
        name: "Wicketkeeper",
      },
      updated_at: "2020-04-07T08:51:02.000000Z",
    },
    {
      resource: "players",
      id: 5,
      country_id: 52126,
      firstname: "Azhar",
      lastname: "Ali",
      fullname: "Azhar Ali",
      image_path: "https://cdn.sportmonks.com/images/cricket/players/5/5.png",
      dateofbirth: "1985-02-19",
      gender: "m",
      battingstyle: "right-hand-bat",
      bowlingstyle: "legbreak",
      position: {
        resource: "positions",
        id: 1,
        name: "Batsman",
      },
      updated_at: "2020-04-01T02:28:23.000000Z",
    },
    {
      resource: "players",
      id: 6,
      country_id: 52126,
      firstname: "Fakhar",
      lastname: "Zaman",
      fullname: "Fakhar Zaman",
      image_path: "https://cdn.sportmonks.com/images/cricket/players/6/6.png",
      dateofbirth: "1990-04-10",
      gender: "m",
      battingstyle: "left-hand-bat",
      bowlingstyle: "slow-left-arm-orthodox",
      position: {
        resource: "positions",
        id: 1,
        name: "Batsman",
      },
      updated_at: "2020-04-02T02:22:22.000000Z",
    },
    {
      resource: "players",
      id: 7,
      country_id: 52126,
      firstname: "Imam",
      lastname: "ul Haq",
      fullname: "Imam ul Haq",
      image_path: "https://cdn.sportmonks.com/images/cricket/players/7/7.png",
      dateofbirth: "1995-12-12",
      gender: "m",
      battingstyle: "left-hand-bat",
      bowlingstyle: null,
      position: {
        resource: "positions",
        id: 1,
        name: "Batsman",
      },
      updated_at: "2020-04-02T09:00:48.000000Z",
    },
    {
      resource: "players",
      id: 8,
      country_id: 52126,
      firstname: "Babar",
      lastname: "Azam",
      fullname: "Babar Azam",
      image_path: "https://cdn.sportmonks.com/images/cricket/players/8/8.png",
      dateofbirth: "1994-10-15",
      gender: "m",
      battingstyle: "right-hand-bat",
      bowlingstyle: "right-arm-offbreak",
      position: {
        resource: "positions",
        id: 1,
        name: "Batsman",
      },
      updated_at: "2020-02-23T10:47:44.000000Z",
    },
    {
      resource: "players",
      id: 9,
      country_id: 52126,
      firstname: "Asad",
      lastname: "Shafiq",
      fullname: "Asad Shafiq",
      image_path: "https://cdn.sportmonks.com/images/cricket/players/9/9.png",
      dateofbirth: "1986-01-28",
      gender: "m",
      battingstyle: "right-hand-bat",
      bowlingstyle: "right-arm-offbreak",
      position: {
        resource: "positions",
        id: 1,
        name: "Batsman",
      },
      updated_at: "2020-03-31T15:33:50.000000Z",
    },
    {
      resource: "players",
      id: 10,
      country_id: 52126,
      firstname: "Haris",
      lastname: "Sohail",
      fullname: "Haris Sohail",
      image_path: "https://cdn.sportmonks.com/images/cricket/players/10/10.png",
      dateofbirth: "1989-01-09",
      gender: "m",
      battingstyle: "left-hand-bat",
      bowlingstyle: "slow-left-arm-orthodox",
      position: {
        resource: "positions",
        id: 4,
        name: "Allrounder",
      },
      updated_at: "2020-04-02T07:30:27.000000Z",
    },
    {
      resource: "players",
      id: 11,
      country_id: 52126,
      firstname: "Usman",
      lastname: "Salahuddin",
      fullname: "Usman Salahuddin",
      image_path: "https://cdn.sportmonks.com/images/cricket/players/11/11.png",
      dateofbirth: "1990-12-02",
      gender: "m",
      battingstyle: "right-hand-bat",
      bowlingstyle: null,
      position: {
        resource: "positions",
        id: 1,
        name: "Batsman",
      },
      updated_at: "2020-04-08T09:10:55.000000Z",
    },
    {
      resource: "players",
      id: 12,
      country_id: 52126,
      firstname: "Yasir",
      lastname: "Shah",
      fullname: "Yasir Shah",
      image_path: "https://cdn.sportmonks.com/images/cricket/players/12/12.png",
      dateofbirth: "1986-05-02",
      gender: "m",
      battingstyle: "right-hand-bat",
      bowlingstyle: "legbreak-googly",
      position: {
        resource: "positions",
        id: 2,
        name: "Bowler",
      },
      updated_at: "2020-04-09T05:17:13.000000Z",
    },
    {
      resource: "players",
      id: 13,
      country_id: 52126,
      firstname: "Shadab",
      lastname: "Khan",
      fullname: "Shadab Khan",
      image_path: "https://cdn.sportmonks.com/images/cricket/players/13/13.png",
      dateofbirth: "1998-10-04",
      gender: "m",
      battingstyle: "right-hand-bat",
      bowlingstyle: "legbreak",
      position: {
        resource: "positions",
        id: 4,
        name: "Allrounder",
      },
      updated_at: "2020-04-07T09:05:03.000000Z",
    },
    {
      resource: "players",
      id: 14,
      country_id: 52126,
      firstname: "Bilal",
      lastname: "Asif",
      fullname: "Bilal Asif",
      image_path: "https://cdn.sportmonks.com/images/cricket/players/14/14.png",
      dateofbirth: "1985-09-24",
      gender: "m",
      battingstyle: "right-hand-bat",
      bowlingstyle: "right-arm-offbreak",
      position: {
        resource: "positions",
        id: 4,
        name: "Allrounder",
      },
      updated_at: "2020-04-01T03:31:48.000000Z",
    },
    {
      resource: "players",
      id: 15,
      country_id: 52126,
      firstname: "Mohammad",
      lastname: "Abbas",
      fullname: "Mohammad Abbas",
      image_path: "https://cdn.sportmonks.com/images/cricket/players/15/15.png",
      dateofbirth: "1990-03-10",
      gender: "m",
      battingstyle: "right-hand-bat",
      bowlingstyle: "right-arm-fast-medium",
      position: {
        resource: "positions",
        id: 2,
        name: "Bowler",
      },
      updated_at: "2020-04-05T06:16:39.000000Z",
    },
    {
      resource: "players",
      id: 16,
      country_id: 52126,
      firstname: "Hasan",
      lastname: "Ali",
      fullname: "Hasan Ali",
      image_path: "https://cdn.sportmonks.com/images/cricket/players/16/16.png",
      dateofbirth: "1994-07-02",
      gender: "m",
      battingstyle: "right-hand-bat",
      bowlingstyle: "right-arm-fast-medium",
      position: {
        resource: "positions",
        id: 2,
        name: "Bowler",
      },
      updated_at: "2020-04-02T08:29:31.000000Z",
    },
    {
      resource: "players",
      id: 17,
      country_id: 52126,
      firstname: "Wahab",
      lastname: "Riaz",
      fullname: "Wahab Riaz",
      image_path: "https://cdn.sportmonks.com/images/cricket/players/17/17.png",
      dateofbirth: "1985-06-28",
      gender: "m",
      battingstyle: "right-hand-bat",
      bowlingstyle: "left-arm-fast",
      position: {
        resource: "positions",
        id: 2,
        name: "Bowler",
      },
      updated_at: "2020-04-09T04:55:16.000000Z",
    },
    {
      resource: "players",
      id: 18,
      country_id: 52126,
      firstname: "Faheem",
      lastname: "Ashraf",
      fullname: "Faheem Ashraf",
      image_path: "https://cdn.sportmonks.com/images/cricket/players/18/18.png",
      dateofbirth: "1994-01-16",
      gender: "m",
      battingstyle: "left-hand-bat",
      bowlingstyle: "right-arm-fast-medium",
      position: {
        resource: "positions",
        id: 11,
        name: "Bowling Allrounder",
      },
      updated_at: "2023-03-15T15:09:49.000000Z",
    },
    {
      resource: "players",
      id: 19,
      country_id: 52126,
      firstname: "Mir",
      lastname: "Hamza",
      fullname: "Mir Hamza",
      image_path: "https://cdn.sportmonks.com/images/cricket/players/19/19.png",
      dateofbirth: "1992-09-10",
      gender: "m",
      battingstyle: "left-hand-bat",
      bowlingstyle: "left-arm-fast-medium",
      position: {
        resource: "positions",
        id: 2,
        name: "Bowler",
      },
      updated_at: "2020-04-05T05:54:08.000000Z",
    },
    {
      resource: "players",
      id: 20,
      country_id: 52126,
      firstname: "Mohammad",
      lastname: "Rizwan",
      fullname: "Mohammad Rizwan",
      image_path: "https://cdn.sportmonks.com/images/cricket/players/20/20.png",
      dateofbirth: "1992-01-01",
      gender: "m",
      battingstyle: "right-hand-bat",
      bowlingstyle: null,
      position: {
        resource: "positions",
        id: 3,
        name: "Wicketkeeper",
      },
      updated_at: "2020-02-23T10:41:51.000000Z",
    },
    {
      resource: "players",
      id: 21,
      country_id: 52126,
      firstname: "Mohammad",
      lastname: "Hafeez",
      fullname: "Mohammad Hafeez",
      image_path: "https://cdn.sportmonks.com/images/cricket/players/21/21.png",
      dateofbirth: "1980-10-17",
      gender: "m",
      battingstyle: "right-hand-bat",
      bowlingstyle: "right-arm-offbreak",
      position: {
        resource: "positions",
        id: 4,
        name: "Allrounder",
      },
      updated_at: "2020-04-05T07:14:20.000000Z",
    },
    {
      resource: "players",
      id: 22,
      country_id: 98,
      firstname: "Tim",
      lastname: "Paine",
      fullname: "Tim Paine",
      image_path: "https://cdn.sportmonks.com/images/cricket/players/22/22.png",
      dateofbirth: "1984-12-08",
      gender: "m",
      battingstyle: "right-hand-bat",
      bowlingstyle: "right-arm-fast-medium",
      position: {
        resource: "positions",
        id: 3,
        name: "Wicketkeeper",
      },
      updated_at: "2020-02-06T04:45:12.000000Z",
    },
    {
      resource: "players",
      id: 23,
      country_id: 98,
      firstname: "Ashton",
      lastname: "Agar",
      fullname: "Ashton Agar",
      image_path: "https://cdn.sportmonks.com/images/cricket/players/23/23.png",
      dateofbirth: "1993-10-14",
      gender: "m",
      battingstyle: "left-hand-bat",
      bowlingstyle: "slow-left-arm-orthodox",
      position: {
        resource: "positions",
        id: 2,
        name: "Bowler",
      },
      updated_at: "2023-03-15T07:40:57.000000Z",
    },
    {
      resource: "players",
      id: 24,
      country_id: 98,
      firstname: "Brendan",
      lastname: "Doggett",
      fullname: "Brendan Doggett",
      image_path: "https://cdn.sportmonks.com/images/cricket/players/24/24.png",
      dateofbirth: "1994-05-03",
      gender: "m",
      battingstyle: "right-hand-bat",
      bowlingstyle: "right-arm-fast-medium",
      position: {
        resource: "positions",
        id: 2,
        name: "Bowler",
      },
      updated_at: "2020-12-14T18:49:35.000000Z",
    },
    {
      resource: "players",
      id: 25,
      country_id: 98,
      firstname: "Aaron",
      lastname: "Finch",
      fullname: "Aaron Finch",
      image_path: "https://cdn.sportmonks.com/images/cricket/players/25/25.png",
      dateofbirth: "1986-11-17",
      gender: "m",
      battingstyle: "right-hand-bat",
      bowlingstyle: "slow-left-arm-orthodox",
      position: {
        resource: "positions",
        id: 1,
        name: "Batsman",
      },
      updated_at: "2023-03-23T07:59:56.000000Z",
    },
    {
      resource: "players",
      id: 26,
      country_id: 98,
      firstname: "Travis",
      lastname: "Head",
      fullname: "Travis Head",
      image_path: "https://cdn.sportmonks.com/images/cricket/players/26/26.png",
      dateofbirth: "1993-12-29",
      gender: "m",
      battingstyle: "left-hand-bat",
      bowlingstyle: "right-arm-offbreak",
      position: {
        resource: "positions",
        id: 8,
        name: "Middle Order Batter",
      },
      updated_at: "2023-03-16T05:00:16.000000Z",
    },
  ];
  return mockD;
}
